- name: Set cluster base version
  ansible.builtin.set_fact:
    __dependencies_url: "https://mirror.openshift.com/pub/openshift-v4/x86_64/dependencies/rhcos/{{ config.cluster_version | cluster_base_version }}/latest"

- name: Check if parent folders exist (and create if needed)
  when: vcenter.parent_folder is defined and vcenter.parent_folder is string
  block:
    - name: Split path into parts
      ansible.builtin.set_fact:
        path_parts: "{{ parent_folder.split('/') | reject('match', '^$') }}"

    - name: Debug path_parts
      ansible.builtin.debug:
        var: path_parts

    - name: Build list of pairs (folder+parent)
      ansible.builtin.set_fact:
        path_pairs: "{{ path_pairs | default([]) + [pair] }}"
      loop: "{{ range(path_parts | length) }}"
      vars:
        path_prefix: "{{ path_parts[:item] | join('/') }}"
        pair: "{{ [path_parts[item], '/' ~ path_prefix] }}"

    - name: Create the vCenter folder by the same name as the cluster, only if it doesn't exist
      community.vmware.vcenter_folder:
        hostname: "{{ vcenter.ip }}"
        username: "{{ vcenter.username }}"
        password: "{{ vcenter.password }}"
        datacenter_name: "{{ vcenter.datacenter }}"
        validate_certs: false
        folder_name: "{{ item[0] }}"
        folder_type: vm
        parent_folder: "{{ item[1] if item[1] not in ['', '/'] else omit }}"
        state: present
      loop: "{{ path_pairs }}"

- name: Create the vCenter folder by the same name as the cluster, only if it doesn't exist
  community.vmware.vcenter_folder:
    hostname: "{{ vcenter.ip }}"
    username: "{{ vcenter.username }}"
    password: "{{ vcenter.password }}"
    datacenter_name: "{{ vcenter.datacenter }}"
    validate_certs: false
    folder_name: "{{ cluster }}"
    folder_type: vm
    parent_folder: "{{ parent_folder | default(omit) }}"
    state: present

- name: Load master ignition file
  ansible.builtin.slurp:
    src: "{{ playbook_dir }}/install-dir/master.ign"
  register: master_content

- name: Load worker ignition file
  ansible.builtin.slurp:
    src: "{{ playbook_dir }}/install-dir/worker.ign"
  register: worker_content

- name: Load bootstrap ignition file
  ansible.builtin.slurp:
    src: "{{ playbook_dir }}/install-dir/bootstrap.ign"
  register: bootstrap_content

- name: Set ova template name
  ansible.builtin.set_fact:
    vcenter: "{{ vcenter | combine({'template_name': 'rhcos-vmware-' + config.cluster_version | product_release_version + '.ova'}, recursive=True) }}"

- name: Download the OVA file to create the VM
  ansible.builtin.include_tasks:
    file: get_ova.yml
  when: use_ova

- name: Create VMs
  ansible.builtin.include_tasks:
    file: "{{ tasks_name }}"
  vars:
    ip_alloc: "{% if dhcp | default(false) %}dhcp{% else %}static{% endif %}"
    medium: "{% if iso | default(false) | bool %}iso{% else %}ova{% endif %}"
    tasks_name: "{% if ip_alloc == 'dhcp' %}{{ ip_alloc }}{% else %}{{ ip_alloc }}-{{ medium }}{% endif %}.yml"

- name: Finish
  ansible.builtin.include_tasks: finish.yml
