---
- name: Initial Environment setup
  hosts: localhost
  gather_facts: True

  environment:
    PATH: "{{ playbook_dir }}/bin:{{ ansible_env.PATH }}"

  tasks:
    - name: Initial setup and checks
      ansible.builtin.import_role:
        name: setup
      tags:
      - always

    - name: Power off and delete the VMs
      environment:
        GOVC_USERNAME: "{{ vcenter.username }}"
        GOVC_PASSWORD: "{{ vcenter.password }}"
        GOVC_URL: "https://{{ vcenter.ip }}"
        GOVC_DATACENTER: "{{ vcenter.datacenter }}"
        GOVC_INSECURE: 1
      ansible.builtin.import_role:
        name: vsphere_vm
        tasks_from: delete-cluster-ova.yml

