---
- hosts: all
  gather_facts: True
  tasks:
    - name: Initial setup and checks
      import_role:
        name: setup
      tags:
      - always

    - name: Set the cache of all the download links
      import_role:
        name: cache

- hosts: localhost
  gather_facts: True
  environment:
    PATH: "{{ playbook_dir }}/bin:{{ ansible_env.PATH }}"
  tasks:
    - name: Run all the common tasks
      import_role:
        name: common

- hosts: webservers
  gather_facts: False
  environment:
    PATH: "{{ playbook_dir }}/bin:{{ ansible_env.PATH }}"
  tasks:
    - name: Set required facts
      set_fact:
        download: "{{ hostvars[groups['all'].0].download }}"
        config: "{{ hostvars[groups['all'].0].config }}"
      when:
        - config is not defined
        - download is not defined
        - inventory_hostname != "localhost"
        
    - name: Copy over generated ignition files to webserver
      import_role:
        name: webserver
        tasks_from: copy_ign_files

    - name: Download Openshift installer files needed for PXE boot
      import_role:
        name: webserver
        tasks_from: download_pxe_installer_files

- hosts: localhost
  gather_facts: False
  environment:
    PATH: "{{ playbook_dir }}/bin:{{ ansible_env.PATH }}"
    GOVC_USERNAME: "{{ vcenter.username }}"
    GOVC_PASSWORD: "{{ vcenter.password }}"
    GOVC_URL: "https://{{ vcenter.ip }}"
    GOVC_DATACENTER: "{{ datacenter }}"
    GOVC_INSECURE: 1
  tasks:
    - name: Create the DHCP based VMs
      environment:
        GOVC_USERNAME: "{{ vcenter.username }}"
        GOVC_PASSWORD: "{{ vcenter.password }}"
        GOVC_URL: "https://{{ vcenter.ip }}"
        GOVC_DATACENTER: "{{ vcenter.datacenter }}"
        GOVC_INSECURE: 1
      vars:
        dhcp: true
      import_role:
        name: vsphere_vm

    - name: Run steps to finish cluster install
      import_role:
        name: finish_install
