---
- name: Initial Environment setup
  hosts: localhost
  gather_facts: True
  environment:
    PATH: "{{ playbook_dir }}/bin:{{ ansible_env.PATH }}"
  vars_files:
  - "{{ clusters_folder }}/{{ cluster }}_additional_nodes_ova.yaml"
  tasks:
    - name: Check for additional nodes file
      stat:
        path: "{{ clusters_folder }}/{{ cluster }}_additional_nodes_ova.yaml"
      register: nodes_file

    - fail:
        msg: "Bailing out: nodes file is not found in the '{{ clusters_folder }}' folder"
      when: not nodes_file.stat.exists

    - name: Initial setup and checks
      import_role:
        name: setup
      tags:
      - always
    
    - name: Fetch the content of the sha256sum.txt from the dependencies downloads page
      uri:
        url: "{{ download.dependencies_url }}/sha256sum.txt"
        return_content: yes
      register: dependencies_content


- name: Deploy VMs and finish cluster install
  hosts: localhost
  gather_facts: True
  environment:
    PATH: "{{ playbook_dir }}/bin:{{ ansible_env.PATH }}"
  vars_files:
  - "{{ clusters_folder }}/{{ cluster }}_additional_nodes_ova.yaml"
  tasks:
    - name: Create, Configure and boot the VMs
      environment:
        GOVC_USERNAME: "{{ vcenter.username }}"
        GOVC_PASSWORD: "{{ vcenter.password }}"
        GOVC_URL: "https://{{ vcenter.ip }}"
        GOVC_DATACENTER: "{{ vcenter.datacenter }}"
        GOVC_INSECURE: 1
      import_role:
        name: vsphere_vm_new_nodes