---
- hosts: localhost
  gather_facts: True
  tasks:
    - name: Initial setup and checks
      import_role:
        name: setup
      tags:
      - always

    - name: Set the cache of all the download links
      import_role:
        name: cache

- hosts: localhost
  gather_facts: True
  environment:
    PATH: "{{ playbook_dir }}/bin:{{ ansible_env.PATH }}"
  tasks:
    - name: Run all the common pre-install tasks
      import_role:
        name: common
        tasks_from: pre_install

- hosts: registries
  gather_facts: False
  tasks:
    - name: Run the setup tasks for a restricted environment
      when: registry.create_registry
      import_role:
        name: restricted
        tasks_from: setup_registry

- hosts: localhost
  gather_facts: False
  tasks:
    - name: Run the tasks for a restricted environment
      import_role:
        name: restricted
        tasks_from: utilize_registry

- hosts: localhost
  gather_facts: False
  environment:
    PATH: "{{ playbook_dir }}/bin:{{ ansible_env.PATH }}"
  tasks:
    - name: Run all the common tasks
      import_role:
        name: common
        tasks_from: install

- hosts: localhost
  gather_facts: False
  environment:
    PATH: "{{ playbook_dir }}/bin:{{ ansible_env.PATH }}"
  tasks:
    - name: Create the DHCP based VMs
      vars:
        static: true
      import_role:
        name: vsphere_vm

    - name: Run steps to finish cluster install
      import_role:
        name: finish_install
