---
- name: Deploy webserver
  ansible.builtin.import_playbook: "{{ playbook_dir }}/playbooks/webservers.yml"

- name: Deploy registry
  ansible.builtin.import_playbook: "{{ playbook_dir }}/playbooks/registry.yml"

- name: Deploy UPI VmWare
  ansible.builtin.import_playbook: "{{ playbook_dir }}/playbooks/upi.yml"

