---
- name: Initial Environment setup
  hosts: localhost
  gather_facts: True
  vars_files:
    - vars/vars.yaml
  environment:
    PATH: "{{ playbook_dir }}/bin:{{ ansible_env.PATH }}"
  tasks:
    - name: Initial setup and checks
      import_role:
        name: setup
      tags:
      - always

    - name: Set the cache of all the download links
      import_role:
        name: cache
      tags:
      - always

    - name: Run all the common tasks
      import_role:
        name: common
      tags:
      - always

    - name: Configure F5
      ansible.builtin.import_role:
        name: f5
      when: f5.enabled | default(false)

- name: Deploy VMs and finish cluster install
  hosts: localhost
  gather_facts: True
  environment:
    PATH: "{{ playbook_dir }}/bin:{{ ansible_env.PATH }}"
  tasks:
    - name: Create, Configure and boot the VMs
      environment:
        GOVC_USERNAME: "{{ vcenter.username }}"
        GOVC_PASSWORD: "{{ vcenter.password }}"
        GOVC_URL: "https://{{ vcenter.ip }}"
        GOVC_DATACENTER: "{{ vcenter.datacenter }}"
        GOVC_INSECURE: 1
      import_role:
        name: vsphere_vm

    - name: Run steps to finish cluster install
      import_role:
        name: finish_install

- name: F5 Cleanup
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Remove bootstrap server from API VIP on f5
      ansible.builtin.import_role:
        name: f5
      vars:
        bootstrap_finished: true
      when: f5.enabled | default(false)
