---
- hosts: localhost
  gather_facts: True
  tasks:
    - name: Initial setup and checks
      import_role:
        name: setup
      tags:
      - always

    - name: Set the cache of all the download links
      import_role:
        name: cache
      tags:
      - pre-install

- hosts: localhost
  gather_facts: True
  environment:
    PATH: "{{ playbook_dir }}/bin:{{ ansible_env.PATH }}"
  tasks:
    - name: Run all the common pre-install tasks
      import_role:
        name: common
        tasks_from: pre_install
      tags:
      - pre-install

- hosts: localhost
  gather_facts: False
  environment:
    PATH: "{{ playbook_dir }}/bin:{{ ansible_env.PATH }}"
  tasks:
    - name: Run all the common tasks
      import_role:
        name: common
        tasks_from: install

- hosts: localhost
  gather_facts: False
  environment:
    PATH: "{{ playbook_dir }}/bin:{{ ansible_env.PATH }}"
    GOVC_USERNAME: "{{ vcenter.admin_username }}"
    GOVC_PASSWORD: "{{ vcenter.admin_password }}"
    GOVC_URL: "https://{{ vcenter.ip }}"
    GOVC_DATACENTER: "{{ vcenter.datacenter }}"
    GOVC_INSECURE: 1
  tasks:
    - name: Create the DHCP based VMs
      vars:
        static: true
      import_role:
        name: vsphere_vm

    - name: Run steps to finish cluster install
      import_role:
        name: finish_install
