---
- name: Initial Environment setup
  hosts: localhost
  gather_facts: True
  environment:
    PATH: "{{ playbook_dir }}/bin:{{ ansible_env.PATH }}"
  tasks:
    - name: Initial setup and checks
      import_role:
        name: setup
      tags:
      - always

    - name: Set the cache of all the download links
      import_role:
        name: cache
      tags:
      - always

    - name: Run all the common tasks
      import_role:
        name: common
      tags:
      - always

    - name: Create, Configure and boot the VMs
      import_role:
        name: vsphere_vm

    - name: Run steps to finish cluster install
      import_role:
        name: finish_install
