- name: Setup vm_list with control plane nodes
  ansible.builtin.set_fact:
    vm_list: "{{ master_vms }}"

- name: Add workers to vm_list if defined
  when: worker_vms is defined
  ansible.builtin.set_fact:
    vm_list: "{{ vm_list + worker_vms }}"

      #- name: Stop control plane and worker VMs
      #  community.vmware.vmware_guest:
      #    hostname: "{{ vcenter.ip }}"
      #    username: "{{ vcenter.username }}"
      #    password: "{{ vcenter.password }}"
      #    datacenter: "{{ vcenter.datacenter }}"
      #    validate_certs: no
      #    folder: "{{ vcenter.folder_absolute_path }}"
      #    name: "{{ item.name }}.{{config.cluster_name}}.{{config.base_domain}}"
      #    state: poweredoff
      #  loop: "{{ vm_list }}"
      #  loop_control:
      #    label: "{{ item.name }} on"

- name: Remove control plane VMs
  community.vmware.vmware_guest:
    hostname: "{{ vcenter.ip }}"
    username: "{{ vcenter.username }}"
    password: "{{ vcenter.password }}"
    datacenter: "{{ vcenter.datacenter }}"
    validate_certs: no
    folder: "{{ vcenter.folder_absolute_path }}"
    name: "{{ item.name }}.{{config.cluster_name}}.{{config.base_domain}}"
    state: absent
  loop: "{{ vm_list }}"
  loop_control:
    label: "{{ item.name }}"
