- name: Create bootstrap and master VMs from the template
  vmware_guest:
    hostname: "{{ vcenter.ip }}"
    username: "{{ vcenter.username }}"
    password: "{{ vcenter.password }}"
    datacenter: "{{ vcenter.datacenter }}"
    validate_certs: no
    folder: "{{ vcenter.folder_absolute_path }}"
    name: "{{ item.name }}.{{config.cluster_name}}.{{config.base_domain}}"
    state: poweredon
    template: "{{ vcenter.folder_absolute_path }}/{{ vcenter.template_name }}"
    disk:
    - size_gb: "{{ item.size_gb | default(120) }}"
      type: thin
      datastore: "{{ vcenter.datastore }}"
    hardware:
      memory_mb: "{{ item.ram | default(16384) }}"
      num_cpus: "{{ item.cpu | default(4) }}"
      memory_reservation_lock: True
      version: "{{ vcenter.hw_version }}"
    networks:
    - name: "{{ vcenter.network }}"
      mac: "{{ item.macaddr | default(omit) }}"
    wait_for_ip_address: no
    advanced_settings:
      - key: guestinfo.ignition.config.data
        value: "{{ bootstrapContent }}"
      - key: guestinfo.ignition.config.data.encoding
        value: base64
      - key: disk.EnableUUID
        value: TRUE
      - key: guestinfo.afterburn.initrd.network-kargs
        value: "ip={{ item.ipaddr }}::{{ static_ip.gateway }}:{{ static_ip.netmask }}:{{ item.name }}.{{config.cluster_name}}.{{config.base_domain}}:ens192:off:{{ static_ip.dns }}"
  loop: "{{ bootstrap_vms + master_vms }}"
  loop_control:
    label: "{{ item.name }}"

- name: Create worker VMs from the template
  vmware_guest:
    hostname: "{{ vcenter.ip }}"
    username: "{{ vcenter.username }}"
    password: "{{ vcenter.password }}"
    datacenter: "{{ vcenter.datacenter }}"
    validate_certs: no
    folder: "{{ vcenter.folder_absolute_path }}"
    name: "{{ item.name }}.{{config.cluster_name}}.{{config.base_domain}}"
    state: poweredoff
    template: "{{ vcenter.folder_absolute_path }}/{{ vcenter.template_name }}"
    disk:
    - size_gb: "{{ item.size_gb | default(120) }}"
      type: thin
      datastore: "{{ vcenter.datastore }}"
    hardware:
      memory_mb: "{{ item.ram | default(16384) }}"
      num_cpus: "{{ item.cpu | default(4) }}"
      memory_reservation_lock: True
      version: "{{ vcenter.hw_version }}"
    networks:
    - name: "{{ vcenter.network }}"
      mac: "{{ item.macaddr | default(omit) }}"
    wait_for_ip_address: no
    advanced_settings:
      - key: guestinfo.ignition.config.data
        value: "{{ workerContent }}"
      - key: guestinfo.ignition.config.data.encoding
        value: base64
      - key: disk.EnableUUID
        value: TRUE
      - key: guestinfo.afterburn.initrd.network-kargs
        value: "ip={{ item.ipaddr }}::{{ static_ip.gateway }}:{{ static_ip.netmask }}:{{ item.name }}.{{config.cluster_name}}.{{config.base_domain}}:ens192:off:{{ static_ip.dns }}"
  loop: "{{ worker_vms }}"
  loop_control:
    label: "{{ item.name }}"
