- name: assert | Make sure networkType is valid when defined
  ansible.builtin.assert:
    that:
      - config.networkType in [ 'OpenShiftSDN', 'OVNKubernetes' ]
    fail_msg:
      - config.networkType = {{ config.networkType }}
      - config.networkType must be OpenShiftSDN or OVNKubernetes
    success_msg: config.network is valid
  when: config.networkType is defined

- name: assert | Make sure isolationMode is valid when defined
  ansible.builtin.assert:
    that:
      - config.isolationMode in [ 'NetworkPolicy', 'Multitenant', 'Subnet' ]
    fail_msg:
      - config.isolationMode = {{ config.isolationMode }}
      - config.isolationMode must be NetworkPolicy, Multitenant, or Subnet
    success_msg: config.isolationMode is valid
  when: config.isolationMode is defined