- name: Make a copy of cluster-network-02-config.yaml to modify
  ansible.builtin.copy:
    mode: "0644"
    src: "{{ playbook_dir }}/install-dir/manifests/cluster-network-02-config.yml"
    dest: "{{ playbook_dir }}/install-dir/manifests/cluster-network-03-config.yml"

- name: Update apiVersion from config to operator
  ansible.builtin.replace:
    regexp: '^(apiVersion:) config(.openshift.io/v1)$'
    replace: '\1 operator\2'
    path: "{{ playbook_dir }}/install-dir/manifests/cluster-network-03-config.yml"

- name: Insert new network for selected isolation
  ansible.builtin.blockinfile:
    insertafter: 'spec:'
    block: |2
        defaultNetwork:
          type: {{ config.networkType | default('OpenShiftSDN') }}
          openshiftSDNConfig:
            mode: {{ config.isolationMode }}
    path: "{{ playbook_dir }}/install-dir/manifests/cluster-network-03-config.yml"
    state: present

- name: Remove networkType line
  ansible.builtin.lineinfile:
    path: "{{ playbook_dir }}/install-dir/manifests/cluster-network-03-config.yml"
    regexp: 'networkType: .+$'
    state: absent

- name: Fix openshiftSDNConfig when not OpenShiftSDN
  ansible.builtin.replace:
    path: "{{ playbook_dir }}/install-dir/manifests/cluster-network-03-config.yml"
    regexp: 'openshiftSDNConfig'
    replace: 'ovnKubernetesConfig'
  when:
    - config.networkType is defined
    - config.networkType == 'OVNKubernetes'
