- name: Print basic info
  ansible.builtin.include_tasks: info.yml

- name: Setup variables
  ansible.builtin.include_tasks: vars.yml

- name: Create ssh keys
  ansible.builtin.include_tasks: ssh.yml
  when: installer_ssh_key is not defined

- name: Include assert
  ansible.builtin.include_tasks: assert.yml

- name: Include dependencies
  ansible.builtin.include_tasks: dependencies.yml

- name: Include binaries
  ansible.builtin.include_tasks: binaries.yml

- name: Include manifests
  ansible.builtin.include_tasks: manifests.yml

- name: Setup ISO file
  ansible.builtin.include_role:
    name: node_isos
  when: use_iso | default(false) and not dhcp | default(false)
