- name: manifests | Generate the ignition manifests
  ansible.builtin.command: "{{ install_dir }}/bin/openshift-install create manifests --dir={{ install_dir }}/install-dir" # noqa no-changed-when
  changed_when: false

- name: manifests | Apply the patch to set mastersSchedulable to false
  ansible.posix.patch:
    src: "cluster-scheduler-02-config.yml.patch"
    dest: "{{ install_dir }}/install-dir/manifests/cluster-scheduler-02-config.yml"
  when: not config.master_schedulable | bool

- name: manifests | Configure custom isolation mode for network provider
  when:
    - config.isolationMode is defined
    - config.isolationMode != "NetworkPolicy"
  ansible.builtin.include_tasks: isolation_mode.yml

- name: manifests | Remove Master Machine manifests
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  with_fileglob:
    - "{{ install_dir }}/install-dir/openshift/99_openshift-cluster-api_master-machines-*.yaml"

- name: manifests | Remove Worker MachineSet manifest
  ansible.builtin.file:
    path: "{{ install_dir }}/install-dir/openshift/99_openshift-cluster-api_worker-machineset-0.yaml"
    state: absent

- name: manifests | Configure custom ntp servers for masters and workers
  when: ntp.custom
  ansible.builtin.include_tasks: configure_ntp.yml

- name: manifests | Generate the ignition configs
  ansible.builtin.command: "{{ install_dir }}/bin/openshift-install create ignition-configs --dir={{ install_dir }}/install-dir" # noqa no-changed-when
