- name: Create the cluster folder on webserver
  become: true
  file:
    path: "/var/www/html/{{ cluster }}/"
    owner: root
    mode: u=rwx,g=rx,o=rx
    group: root
    state: directory

- name: Create the cluster ignition folder on webserver
  become: true
  file: 
    path: "/var/www/html/{{ cluster }}/ignition/"
    owner: root
    mode: u=rwx,g=rx,o=rx
    group: root
    state: directory

- name: Create the cluster install folder on webserver
  become: true
  file: 
    path: "/var/www/html/{{ cluster }}/install/"
    owner: root
    mode: u=rwx,g=rx,o=rx
    group: root
    state: directory
