- name: Downloading OpenShift installer initramfs
  become: true
  ansible.builtin.get_url:
    url: "{{ download.initramfs }}"
    dest: /var/lib/tftpboot/rhcos/initramfs.img
    force: true
    mode: "0555"
    validate_certs: false

- name: Downloading OpenShift installer kernel
  become: true
  ansible.builtin.get_url:
    url: "{{ download.kernel }}"
    dest: /var/lib/tftpboot/rhcos/kernel
    force: true
    mode: "0555"
    validate_certs: false
