---
- name: Deploy the Openshift
  hosts: openshift
  gather_facts: true
  environment:
    PATH: "{{ install_dir }}/bin:{{ ansible_env.PATH }}"
    GOVC_USERNAME: "{{ vcenter.username }}"
    GOVC_PASSWORD: "{{ vcenter.password }}"
    GOVC_URL: "https://{{ vcenter.ip }}"
    GOVC_DATACENTER: "{{ vcenter.datacenter }}"
    GOVC_INSECURE: "1"
  pre_tasks:
    - debug:
        var: "ansible_env.HOME"
  roles:
    - role: configure_dns
      when: dns_provider is defined
    - role: configure_lb
      when: lb_provider is defined
    - role: setup
    - role: deploy
