---
- name: Deploy the Openshift
  hosts: openshift
  gather_facts: true
  environment:
    PATH: "{{ playbook_dir }}/bin:{{ ansible_env.PATH }}"
    GOVC_USERNAME: "{{ vcenter.username }}"
    GOVC_PASSWORD: "{{ vcenter.password }}"
    GOVC_URL: "https://{{ vcenter.ip }}"
    GOVC_DATACENTER: "{{ vcenter.datacenter }}"
    GOVC_INSECURE: "1"
  roles:
    - role: configure_dns
    - role: configure_lb
    - role: setup
    - role: deploy
